export const admissionForm = {
  title: 'COLLEGE ADMISSION FORM',
  description:
    "If you'd like to apply to our college, please fill in this College Admission Form and we will contact you as soon as possible.",
  formSections: [
    {
      sectionTitle: 'Personal Information',
      sectionDescription: 'Please fill out your personal information.',
      sectionFields: [
        {
          id: '1',
          type: 'text',
          label: 'First Name',
          name: 'firstName',
          value: '',
          visible: true,
          placeholder: 'Enter your first name',
          validationRules: {
            required: true,
            minLength: 1,
            maxLength: 100,
          },
        },
        {
          id: '2',
          type: 'text',
          label: 'Middle Name',
          name: 'middleName',
          value: '',
          visible: true,
          placeholder: 'Enter your middle name',
          validationRules: {
            required: false,
            minLength: 1,
            maxLength: 100,
          },
        },
        {
          id: '3',
          type: 'text',
          label: 'Last Name',
          name: 'lastName',
          value: '',
          visible: true,
          placeholder: 'Enter your last name',
          validationRules: {
            required: true,
            minLength: 1,
            maxLength: 100,
          },
        },
        {
          id: '4',
          type: 'email',
          label: 'Email',
          name: 'emailId',
          value: '',
          visible: true,
          placeholder: 'Enter your email',
          validationRules: {
            required: true,
            email: true,
          },
        },
        {
          id: '5',
          type: 'text',
          label: 'Contact Number',
          name: 'contactNumber',
          value: '',
          visible: true,
          placeholder: 'Enter your contact number',
          validationRules: {
            required: true,
          },
        },
        {
          id: '6',
          type: 'date',
          label: 'Date of Birth',
          name: 'dob',
          value: '',
          visible: true,
          placeholder: 'select your DOB',
          validationRules: {
            required: true,
          },
        },
        {
          id: '7',
          type: 'radio',
          label: 'Gender',
          name: 'gender',
          value: '',
          visible: true,
          options: [
            {
              label: 'Male',
              value: 'male',
            },
            {
              label: 'Female',
              value: 'female',
            },
          ],
          validationRules: {
            required: true,
          },
        },

        {
          id: '8',
          type: 'text',
          label: "Father's Name",
          name: 'fatherName',
          value: '',
          visible: true,
          placeholder: 'enter your father name',
          validationRules: {
            required: true,
          },
        },
        {
          id: '9',
          type: 'text',
          label: "Father's Occupation",
          name: 'fatherOccupation',
          value: '',
          visible: true,
          placeholder: 'enter your father name',
          validationRules: {
            required: true,
          },
        },
        {
          id: '10',
          type: 'text',
          label: "Mother's Name",
          name: 'motherName',
          value: '',
          visible: true,
          placeholder: 'enter your father occupation',
          validationRules: {
            required: true,
          },
        },
        {
          id: '11',
          type: 'text',
          label: "Mother's Occupation",
          name: 'motherOccupation',
          value: '',
          visible: true,
          placeholder: 'enter your mother occupation',
          validationRules: {
            required: true,
          },
        },
        {
          id: '12',
          type: 'text',
          label: "Guardian's Name",
          name: 'guardianName',
          value: '',
          visible: true,
          placeholder: 'enter your guardian name',
          validationRules: {
            required: true,
          },
        },
        {
          id: '13',
          type: 'text',
          label: 'Address Line 1',
          name: 'addressLine1',
          value: '',
          visible: true,
          placeholder: 'address line 1',
          validationRules: {
            required: true,
          },
        },
        {
          id: '14',
          type: 'text',
          label: 'Address Line 2',
          name: 'addressLine2',
          value: '',
          visible: true,
          placeholder: 'address line 2',
          validationRules: {
            required: true,
          },
        },
        {
          id: '15',
          type: 'text',
          label: 'Nationality',
          name: 'nationality',
          value: '',
          visible: true,
          placeholder: 'enter nationality',
          validationRules: {
            required: true,
          },
        },
        {
          id: '16',
          type: 'text',
          label: 'State',
          name: 'state',
          value: '',
          visible: true,
          placeholder: 'enter state',
          validationRules: {
            required: true,
          },
        },
        {
          id: '17',
          type: 'text',
          label: 'District',
          name: 'district',
          value: '',
          visible: true,
          placeholder: 'enter district',
          validationRules: {
            required: true,
          },
        },
        {
          id: '18',
          type: 'text',
          label: 'Postal / ZIP Code',
          name: 'postalCode',
          value: '',
          visible: true,
          placeholder: 'enter postal/zip code',
          validationRules: {
            required: true,
          },
        },
        {
          id: '19',
          type: 'text',
          label: 'Religion',
          name: 'religion',
          value: '',
          visible: true,
          placeholder: 'enter your relegion',
          validationRules: {
            required: true,
          },
        },
        {
          id: '20',
          type: 'text',
          label: 'Community',
          name: 'community',
          value: '',
          visible: true,
          placeholder: 'enter your community',
          validationRules: {
            required: true,
          },
        },
        {
          id: '21',
          type: 'text',
          label: 'Caste',
          name: 'caste',
          value: '',
          visible: true,
          placeholder: 'enter your caste',
          validationRules: {
            required: true,
          },
        },
      ],
    },
  ],
};

export const EnquiryForm = {
  title: 'COLLEGE ENQUIRY FORM',
  description:
    "If you'd like to apply to our college, please fill in this College Enquiry Form and we will contact you as soon as possible.",
  formSections: [
    {
      sectionTitle: 'Personal Information',
      sectionDescription: 'Please fill out your personal information.',
      sectionFields: [
        {
          id: '1',
          type: 'text',
          label: 'Name',
          name: 'name',
          value: '',
          visible: true,
          placeholder: 'Enter your name',
          validationRules: {
            required: true,
            minLength: 1,
            maxLength: 100,
          },
        },
        {
          id: '2',
          type: 'date',
          label: 'Date',
          name: 'date',
          value: '',
          visible: true,
          placeholder: 'select todays date',
          validationRules: {
            required: true,
          },
        },
        {
          id: '3',
          type: 'email',
          label: 'Email',
          name: 'emailId',
          value: '',
          visible: true,
          placeholder: 'Enter your email',
          validationRules: {
            required: true,
            email: true,
          },
        },
        {
          id: '4',
          type: 'text',
          label: 'Contact Number',
          name: 'contactNumber',
          value: '',
          visible: true,
          placeholder: 'Enter your contact number',
          validationRules: {
            required: true,
          },
        },
        {
          id: '5',
          type: 'date',
          label: 'Date of Birth',
          name: 'dob',
          value: '',
          visible: true,
          placeholder: 'select your DOB',
          validationRules: {
            required: true,
          },
        },
        {
          id: '6',
          type: 'text',
          label: 'Age',
          name: 'age',
          value: '',
          visible: true,
          placeholder: 'Enter your age',
          validationRules: {
            required: true,
          },
        },
        {
          id: '7',
          type: 'radio',
          label: 'Gender',
          name: 'gender',
          value: '',
          visible: true,
          options: [
            {
              label: 'Male',
              value: 'male',
            },
            {
              label: 'Female',
              value: 'female',
            },
          ],
          validationRules: {
            required: true,
          },
        },
        {
          id: '8',
          type: 'radio',
          label: 'Marital Status',
          name: 'maritalStatus',
          value: '',
          visible: true,
          options: [
            {
              label: 'Married',
              value: 'married',
            },
            {
              label: 'Single',
              value: 'single',
            },
          ],
          validationRules: {
            required: true,
          },
        },
        {
          id: '9',
          type: 'text',
          label: "Father's Name",
          name: 'fatherName',
          value: '',
          visible: true,
          placeholder: 'enter your father name',
          validationRules: {
            required: true,
          },
        },
        {
          id: '10',
          type: 'text',
          label: "Father's Occupation",
          name: 'fatherOccupation',
          value: '',
          visible: true,
          placeholder: 'enter your father name',
          validationRules: {
            required: true,
          },
        },
        {
          id: '11',
          type: 'text',
          label: "Mother's Name",
          name: 'motherName',
          value: '',
          visible: true,
          placeholder: 'enter your father occupation',
          validationRules: {
            required: true,
          },
        },
        {
          id: '12',
          type: 'text',
          label: "Mother's Occupation",
          name: 'motherOccupation',
          value: '',
          visible: true,
          placeholder: 'enter your mother occupation',
          validationRules: {
            required: true,
          },
        },
        {
          id: '13',
          type: 'text',
          label: "Guardian's Name",
          name: 'guardianName',
          value: '',
          visible: true,
          placeholder: 'enter your guardian name',
          validationRules: {
            required: true,
          },
        },
        {
          id: '14',
          type: 'text',
          label: "Guardian's Occupation",
          name: 'guardianOccupation',
          value: '',
          visible: true,
          placeholder: 'enter your guardian occupation',
          validationRules: {
            required: true,
          },
        },
        {
          id: '15',
          type: 'text',
          label: 'Address Line 1',
          name: 'addressLine1',
          value: '',
          visible: true,
          placeholder: 'address line 1',
          validationRules: {
            required: true,
          },
        },
        {
          id: '16',
          type: 'text',
          label: 'Address Line 2',
          name: 'addressLine2',
          value: '',
          visible: true,
          placeholder: 'address line 2',
          validationRules: {
            required: true,
          },
        },
        {
          id: '17',
          type: 'text',
          label: 'Nationality',
          name: 'nationality',
          value: '',
          visible: true,
          placeholder: 'enter nationality',
          validationRules: {
            required: true,
          },
        },
        {
          id: '18',
          type: 'text',
          label: 'State',
          name: 'state',
          value: '',
          visible: true,
          placeholder: 'enter state',
          validationRules: {
            required: true,
          },
        },
        {
          id: '19',
          type: 'text',
          label: 'District',
          name: 'district',
          value: '',
          visible: true,
          placeholder: 'enter district',
          validationRules: {
            required: true,
          },
        },
        {
          id: '20',
          type: 'text',
          label: 'Postal / ZIP Code',
          name: 'postalCode',
          value: '',
          visible: true,
          placeholder: 'enter postal/zip code',
          validationRules: {
            required: true,
          },
        },
        {
          id: '21',
          type: 'text',
          label: 'School Name (10th std)',
          name: 'schoolName10th',
          value: '',
          visible: true,
          placeholder: 'enter your school name',
          validationRules: {
            required: true,
          },
        },
        {
          id: '22',
          type: 'text',
          label: 'Year of Passing',
          name: 'yearOfPassing10th',
          value: '',
          visible: true,
          placeholder: 'enter year of passing',
          validationRules: {
            required: true,
          },
        },
        {
          id: '23',
          type: 'text',
          label: 'Obtained Mark',
          name: 'obtainedMark10th',
          value: '',
          visible: true,
          placeholder: 'enter your mark',
          validationRules: {
            required: true,
          },
        },
        {
          id: '24',
          type: 'text',
          label: 'Medium of Education',
          name: 'mediumOfEducation10th',
          value: '',
          visible: true,
          placeholder: 'enter year medium of education',
          validationRules: {
            required: true,
          },
        },
        {
          id: '25',
          type: 'text',
          label: 'School Name (12th std)',
          name: 'schoolName12th',
          value: '',
          visible: true,
          placeholder: 'enter your school name',
          validationRules: {
            required: true,
          },
        },
        {
          id: '26',
          type: 'text',
          label: 'Year of Passing',
          name: 'yearOfPassing12th',
          value: '',
          visible: true,
          placeholder: 'enter year of passing',
          validationRules: {
            required: true,
          },
        },
        {
          id: '27',
          type: 'text',
          label: 'Obtained Mark',
          name: 'obtainedMark12th',
          value: '',
          visible: true,
          placeholder: 'enter your mark',
          validationRules: {
            required: true,
          },
        },
        {
          id: '28',
          type: 'text',
          label: 'Medium of Education',
          name: 'mediumOfEducation12th',
          value: '',
          visible: true,
          placeholder: 'enter year medium of education',
          validationRules: {
            required: true,
          },
        },
      ],
    },
  ],
};

export const departmentForm = {
  title: 'DEPARTMENT FORM',
  formSections: [
    {
      sectionFields: [
        {
          id: '1',
          type: 'text',
          label: 'Department Name',
          name: 'departmentName',
          value: '',
          visible: true,
          placeholder: 'Enter your department name',
          validationRules: {
            required: true,
            minLength: 1,
            maxLength: 100,
          },
        },
        {
          id: '2',
          type: 'text',
          label: 'No of Years',
          name: 'noOfYears',
          value: '',
          visible: true,
          placeholder: 'Enter no of years',
          validationRules: {
            required: false,
            minLength: 1,
            maxLength: 100,
          },
        },
        {
          id: '3',
          type: 'text',
          label: 'Department Code',
          name: 'departmentCode',
          value: '',
          visible: true,
          placeholder: 'Enter your Department Code',
          validationRules: {
            required: true,
            minLength: 1,
            maxLength: 100,
          },
        },
        {
          id: '4',
          type: 'radio',
          label: 'Active Status',
          name: 'activeStatus',
          value: '',
          visible: true,
          options: [
            {
              label: 'Active',
              value: 'active',
            },
            {
              label: 'Inactive',
              value: 'inactive',
            },
          ],
          validationRules: {
            required: true,
          },
        },
        {
          id: '5',
          type: 'text',
          label: 'Note/Description',
          name: 'description',
          value: '',
          visible: true,
          placeholder: 'Enter Note/Description',
          validationRules: {
            required: true,
          },
        },       
      ],
    },
  ],
};