/*
  Warnings:

  - You are about to drop the column `address` on the `Staff` table. All the data in the column will be lost.
  - You are about to drop the column `annualIncome` on the `Staff` table. All the data in the column will be lost.
  - You are about to drop the column `dob` on the `Staff` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "Staff" DROP COLUMN "address",
DROP COLUMN "annualIncome",
DROP COLUMN "dob",
ADD COLUMN     "birthCertificate" TEXT,
ADD COLUMN     "caste" TEXT,
ADD COLUMN     "characterCertificate" TEXT,
ADD COLUMN     "childImmunicationCertificate" TEXT,
ADD COLUMN     "communityCertificate" TEXT,
ADD COLUMN     "covidVaccinationCertificate" TEXT,
ADD COLUMN     "currentAddressLine1" TEXT,
ADD COLUMN     "currentAddressLine2" TEXT,
ADD COLUMN     "currentCity" TEXT,
ADD COLUMN     "currentCountry" TEXT,
ADD COLUMN     "currentPincode" TEXT,
ADD COLUMN     "currentState" TEXT,
ADD COLUMN     "dateOfBirth" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "degreeMarksCard" TEXT,
ADD COLUMN     "differentlyAbled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "email" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "enrollmentNumber" TEXT,
ADD COLUMN     "epfNumber" TEXT,
ADD COLUMN     "fatherName" TEXT,
ADD COLUMN     "fatherOccupation" TEXT,
ADD COLUMN     "fathersPhoto" TEXT,
ADD COLUMN     "firstName" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "gender" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "image" TEXT,
ADD COLUMN     "incomeCertificate" TEXT,
ADD COLUMN     "lastName" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "medicalCertificate" TEXT,
ADD COLUMN     "middleName" TEXT DEFAULT '',
ADD COLUMN     "mobile" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "motherName" TEXT,
ADD COLUMN     "motherOccupation" TEXT,
ADD COLUMN     "motherTongue" TEXT,
ADD COLUMN     "mothersPhoto" TEXT,
ADD COLUMN     "nationality" TEXT,
ADD COLUMN     "otherCertificate" TEXT,
ADD COLUMN     "permanentAddress1" TEXT,
ADD COLUMN     "permanentAddress2" TEXT,
ADD COLUMN     "permanentCity" TEXT,
ADD COLUMN     "permanentCountry" TEXT,
ADD COLUMN     "permanentPincode" TEXT,
ADD COLUMN     "permanentState" TEXT,
ADD COLUMN     "pgMarksCard" TEXT,
ADD COLUMN     "pucMarksCard" TEXT,
ADD COLUMN     "religion" TEXT,
ADD COLUMN     "specialCategory" TEXT,
ADD COLUMN     "spouseName" TEXT,
ADD COLUMN     "spouseOccupation" TEXT,
ADD COLUMN     "spousePhoto" TEXT,
ADD COLUMN     "sslcMarksCard" TEXT,
ADD COLUMN     "transferCertificate" TEXT,
ALTER COLUMN "type" SET DEFAULT 'Teaching',
ALTER COLUMN "aadharCardNumber" DROP NOT NULL,
ALTER COLUMN "bloodGroup" DROP NOT NULL,
ALTER COLUMN "status" SET DEFAULT 'Active';
